baseURL = 'https://simkrae.github.io/blog/'
title = 'Journal'
theme = 'PaperMod'

# Language settings (Monolingual English)
languageCode = "en"
defaultContentLanguage = "en"

[outputs]
home = ["HTML", "RSS"]
section = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML"]

[params]
    env = "production"
    [params.author]
        name = "Journal"
    showReadingTime = true
    displayFullContent = false
    ShowPostNavLinks = true
    showLanguageSelector = false 

    [params.homeInfoParams]
        Title = "Documentation & Research"
        Content = "Technical logs regarding software development and automated trading."

    [params.editPost]
        URL = "https://github.com/simkrae/blog/tree/main/content"
        Text = "Suggest Changes"
        appendFilePath = true

[[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 10

[markup.highlight]
    noClasses = false

# Automatic URL structure
[permalinks]
    posts = '/posts/:year/:month/:slug/'
